# Generated by Django 2.0 on 2021-05-11 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Duration_of_seconds', models.DurationField()),
                ('Uploaded_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Title_audiobook', models.FileField(upload_to='audio/')),
                ('Author_title', models.CharField(max_length=100)),
                ('Narrator', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'AudioBook',
                'verbose_name_plural': 'AudioBooks',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Duration_of_seconds', models.DurationField()),
                ('Uploaded_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Name_of_Podcast', models.FileField(upload_to='podcast/')),
                ('Host', models.CharField(max_length=100)),
                ('Participants', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Duration_of_seconds', models.DurationField()),
                ('Uploaded_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Name_of_song', models.FileField(upload_to='songs/')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
